/* Aura Apparel - router, pages, checkout. Vanilla JS, no build step. */
const NAV=[["Shop All","#/shop"],["Men","#/shop/men"],["Women","#/shop/women"],["New Arrivals","#/new"],["Limited Stock","#/limited"],["Deals","#/sale"],["Stores","#/stores"]];
let query="",sort="feat",lastMsg="";
const isSale=p=>p.sale&&p.sale<p.price;
const card=p=>{const im=p.imgs[0];return `<article class="card"><a href="#/p/${p.id}"><div class="im"><img src="${esc(im)}" alt="${esc(p.name)}" loading="lazy" width="600" height="800">${isSale(p)?`<span class="tag">-${Math.round(100-price(p)/p.price*100)}%</span>`:""}${p.stock>0&&p.stock<=5?`<span class="tag lo">Only ${p.stock} left</span>`:""}${p.stock<1?'<span class="tag lo">Sold out</span>':""}</div></a><button class="heart" data-heart="${p.id}" aria-label="Wishlist">${Cart.wish.includes(p.id)?"♥":"♡"}</button><a href="#/p/${p.id}"><small>${esc((CATS.find(c=>c[0]===p.cat)||[])[1]||"")}</small><h3>${esc(p.name)}</h3><div class="pr">${fmt(price(p))}${isSale(p)?`<s>${fmt(p.price)}</s>`:""}</div></a></article>`};
const filters={men:p=>p.g!=="Women",women:p=>p.g!=="Men"};
function listing(title,desc,fn,active){
 let L=getProducts().filter(fn);const q=query.trim().toLowerCase();
 if(q)L=L.filter(p=>(p.name+" "+p.desc+" "+p.tags.join(" ")+" "+p.cat).toLowerCase().includes(q));
 if(sort==="lo")L.sort((a,b)=>price(a)-price(b));else if(sort==="hi")L.sort((a,b)=>price(b)-price(a));
 return `<div class="wrap"><div style="padding-top:40px"><h1 style="font-size:36px">${esc(title)}</h1><p style="color:var(--mut)">${esc(desc)}</p></div><div class="shop"><div class="fil"><h4>Collections</h4><button class="${active==="all"?"on":""}" data-go="#/shop">All Products</button>${CATS.map(c=>`<button class="${active===c[0]?"on":""}" data-go="#/shop/${c[0]}">${esc(c[1])}</button>`).join("")}</div><div><div class="bar"><span style="color:var(--mut)">${L.length} product${L.length===1?"":"s"}${q?` for "${esc(q)}"`:""}${q?' <button data-clear><u>clear</u></button>':""}</span><select id="sort" aria-label="Sort"><option value="feat">Featured</option><option value="lo" ${sort==="lo"?"selected":""}>Price: Low to High</option><option value="hi" ${sort==="hi"?"selected":""}>Price: High to Low</option></select></div>${L.length?`<div class="grid g3">${L.map(card).join("")}</div>`:'<p class="empty">No products match. Try another search or collection.</p>'}</div></div></div>`}
function home(){const P=getProducts(),f=P.filter(p=>p.f).slice(0,4);
 return `<section class="hero"><img src="assets/images/hero.jpg" alt="Aura Apparel campaign" fetchpriority="high"><div class="in"><div class="eyebrow">Export Overstock · I-8 Markaz</div><h1>Premium Apparel. Unexpected Prices.</h1><p>Discover export-quality fashion, limited pieces and premium finds at prices far below traditional retail. Visit our twin stores in I-8 Markaz, Islamabad or shop online nationwide.</p><div class="row"><a class="btn w" href="#/shop">Shop the Drop →</a><a class="btn o" style="color:#fff;border-color:#fff" href="#/stores">Visit Our Stores</a></div></div></section>
 <section class="sec"><div class="wrap"><div class="sh"><div><h2>Featured Pieces</h2><p>Hand-picked export surplus. Once it's gone, it's gone.</p></div><a href="#/shop"><u>View all</u></a></div><div class="grid">${f.map(card).join("")}</div></div></section>
 <section class="sec alt"><div class="wrap"><div class="grid g2"><a class="tile" href="#/shop/men"><img src="assets/images/mens.jpg" alt="Men's collection" loading="lazy"><div><h3>Men's Collection</h3><p>Chore Jackets · Oxford Shirts · Heavy Tees · Denim</p></div></a><a class="tile" href="#/shop/women"><img src="assets/images/womens.jpg" alt="Women's collection" loading="lazy"><div><h3>Women's Collection</h3><p>Wool Trench Coats · Knitwear · Relaxed Trousers</p></div></a></div></div></section>
 <section class="sec"><div class="wrap"><div class="center"><span class="eyebrow">The Aura Model</span><h2>Why Aura Apparel?</h2><p style="color:var(--mut);font-size:13px">We bridge the gap between premium global garment manufacturing and honest Pakistani retail pricing.</p></div><div class="grid">${[["Premium Export Apparel","Grade-A fabrications produced in certified Pakistani textile mills for top European and American brand houses."],["Limited Stock Pieces","Every shipment is unique with limited quantities. Once a style sells out, it is not reproduced or restocked."],["Regular Weekly Drops","Fresh inventory arrives every week at our twin retail stores in I-8 Markaz, Islamabad, providing new discoveries on every visit."],["50-70% Below Retail","Cut through massive international brand markups. Premium heavyweight cotton, wool blends, and selvedge denim at fair prices."]].map(b=>`<div class="box"><h3>${b[0]}</h3><p>${b[1]}</p></div>`).join("")}</div></div></section>
 <section class="sec dk"><div class="wrap"><div class="grid g2" style="align-items:center;gap:40px"><div><span class="eyebrow">Visit Us</span><h2 style="color:#fff;font-size:34px;margin:8px 0 14px">Twin Stores in I-8 Markaz</h2>${storeBlocks()}<div class="row"><a class="btn w" href="${CONFIG.maps}" target="_blank" rel="noopener">Open in Google Maps</a></div></div><img src="assets/images/store.jpg" alt="Aura Apparel boutique interior" loading="lazy" style="border-radius:4px;aspect-ratio:4/3;object-fit:cover;width:100%"></div></div></section>`}
const storeBlocks=()=>CONFIG.stores.map((s,i)=>`<p style="color:#d4d4d4;margin-bottom:12px"><b style="color:#fff">Branch ${i+1}: ${esc(s.name.replace("Aura Apparel - ",""))}</b><br>${esc(s.addr)}<br><span style="color:#a3a3a3">${esc(s.note)}</span></p>`).join("")+`<p style="color:#a3a3a3;font-size:12px"><b style="color:#e5e5e5">Retail Hours</b><br>${CONFIG.hours.map(h=>h[0]+": "+h[1]).join("<br>")}</p>`;
let sel={};
function detail(id){const p=find(id);if(!p)return '<p class="empty">Product not found. <a href="#/shop"><u>Back to shop</u></a></p>';
 sel={img:0,size:p.sizes[0],color:p.colors[0]?.name||"Default"};
 return `<div class="wrap"><div class="pd"><div><div class="main"><img id="mi" src="${esc(p.imgs[0])}" alt="${esc(p.name)}"></div><div class="thumbs">${p.imgs.map((s,i)=>`<img src="${esc(s)}" alt="View ${i+1}" data-th="${i}" class="${i?"":"on"}" loading="lazy">`).join("")}</div></div><div><span class="eyebrow">${esc((CATS.find(c=>c[0]===p.cat)||[])[1]||"")}</span><h1>${esc(p.name)}</h1><div class="pr">${fmt(price(p))}${isSale(p)?`<s>${fmt(p.price)}</s>`:""}</div><p style="margin:14px 0;color:var(--mut)">${esc(p.desc)}</p>${p.stock>0&&p.stock<=5?`<p style="color:#b45309;font-weight:600">Only ${p.stock} left, no restock.</p>`:""}
 <div class="opt"><h4>Size</h4><div id="sizes">${p.sizes.map((s,i)=>`<button class="chip ${i?"":"on"}" data-size="${esc(s)}">${esc(s)}</button>`).join("")}</div></div>
 <div class="opt"><h4>Colour: <span id="cn">${esc(sel.color)}</span></h4>${p.colors.map((c,i)=>`<span class="sw ${i?"":"on"}" style="background:${esc(c.hex)}" title="${esc(c.name)}" data-color="${esc(c.name)}" role="button" tabindex="0"></span>`).join("")}</div>
 <div class="row"><button class="btn" style="flex:1" data-add="${p.id}" ${p.stock<1?"disabled":""}>${p.stock<1?"Sold out":"Add to Bag"}</button><button class="btn o" data-heart="${p.id}">${Cart.wish.includes(p.id)?"♥ Saved":"♡ Save"}</button></div>
 <dl>${[["Fabric",p.fabric],["Fit",p.fit],["Care",p.care],["Origin",p.origin],["Delivery","Free over "+fmt(CONFIG.freeOver)+", else "+fmt(CONFIG.shipFee)+". Cash on delivery."]].filter(r=>r[1]).map(r=>`<dt>${r[0]}</dt><dd>${esc(r[1])}</dd>`).join("")}</dl></div></div></div>`}
function checkout(){if(!Cart.items.length)return '<div class="wrap"><p class="empty">Your bag is empty. <a href="#/shop"><u>Continue shopping</u></a></p></div>';
 const fl=(n,l,t="text",r=1)=>`<div class="fld"><label>${l}</label><input name="${n}" type="${t}" ${r?"required":""} autocomplete="${n}"></div>`;
 return `<div class="wrap"><div class="co"><form id="cf" class="card-box"><h1 style="font-size:28px;margin-bottom:18px">Checkout</h1><div class="f2">${fl("name","Full name")}${fl("phone","Phone","tel")}</div>${fl("email","Email","email")}${fl("address","Delivery address")}<div class="f2">${fl("city","City")}${fl("postal","Postal code","text",0)}</div><div class="fld"><label>Order notes (optional)</label><textarea name="notes" rows="2"></textarea></div><p style="font-size:12px;color:var(--mut);margin-bottom:14px"><b>Payment:</b> Cash on delivery. This site has no server: your order is sent to us as a WhatsApp message, which we confirm by phone.</p><button class="btn wa blk">Send Order via WhatsApp</button></form><aside class="card-box" style="align-self:start"><h3 style="margin-bottom:8px">Order Summary</h3>${Cart.items.map(i=>{const p=find(i.id);return `<div class="ci"><img src="${esc(p.imgs[0])}" alt=""><div><b>${esc(p.name)}</b><small>${esc(i.size)} · ${esc(i.color)} · Qty ${i.qty}</small><small>${fmt(price(p)*i.qty)}</small></div></div>`}).join("")}<div style="margin-top:12px">${Cart.summary()}</div></aside></div></div>`}
function order(f){const d=Object.fromEntries(new FormData(f));
 let m=`*New Order - ${CONFIG.brand}*\n\n*Customer*\nName: ${d.name}\nPhone: ${d.phone}\nEmail: ${d.email}\nAddress: ${d.address}, ${d.city}${d.postal?" "+d.postal:""}\n\n*Items*\n`;
 Cart.items.forEach((i,n)=>{const p=find(i.id);m+=`${n+1}. ${p.name} (${i.size}, ${i.color}) x${i.qty} = ${fmt(price(p)*i.qty)}\n`});
 m+=`\nSubtotal: ${fmt(Cart.sub())}\nShipping: ${Cart.ship()?fmt(Cart.ship()):"Free"}\n*Total: ${fmt(Cart.total())}* (Cash on delivery)`+(d.notes?`\n\nNotes: ${d.notes}`:"");
 lastMsg="https://wa.me/"+CONFIG.whatsapp+"?text="+encodeURIComponent(m);window.open(lastMsg,"_blank");Cart.clear();
 $("#app").innerHTML=`<div class="wrap"><div class="page"><h1>Order ready to send</h1><p>WhatsApp should have opened with your order filled in. Press <b>Send</b> there to place it. We will call to confirm.</p><p><a class="btn wa" href="${lastMsg}" target="_blank" rel="noopener">Open WhatsApp again</a> <a class="btn o" href="#/shop">Continue shopping</a></p></div></div>`}
const FAQ=[["How does ordering work?","Add items to your bag, then send your order through WhatsApp. We confirm by phone and dispatch."],["Do you offer cash on delivery?","Yes, cash on delivery is available across Pakistan."],["How much is shipping?","Rs. 250 standard, free on orders over Rs. 3,500. 1-2 days for Islamabad & Rawalpindi, 3-5 days nationwide."],["Will sold-out pieces be restocked?","No. Every shipment is unique and limited."]];
const pages={
 stores:()=>`<div class="wrap"><div class="page"><h1>Our Stores</h1><p>Open 7 days a week in I-8 Markaz, Islamabad.</p>${CONFIG.stores.map(s=>`<div class="box" style="margin-bottom:16px"><h3>${esc(s.name)}</h3><p>${esc(s.addr)}</p><p>${esc(s.note)}</p></div>`).join("")}<p>${CONFIG.hours.map(h=>h[0]+": "+h[1]).join("<br>")}</p><p><a class="btn" href="${CONFIG.maps}" target="_blank" rel="noopener">Open in Google Maps</a></p></div></div>`,
 about:()=>`<div class="wrap"><div class="page"><h1>About Aura Apparel</h1><p>Premium Export Apparel. Unexpected Prices. We bridge the gap between premium global garment manufacturing and honest Pakistani retail pricing, with limited-stock export overstock, fresh weekly drops and no restocks.</p><img src="assets/images/flatlay.jpg" alt="Export overstock flatlay" loading="lazy" style="border-radius:4px;margin:20px 0"><h2 style="margin:20px 0 6px">FAQ</h2>${FAQ.map(f=>`<details><summary>${f[0]}</summary><p style="margin-top:8px">${f[1]}</p></details>`).join("")}</div></div>`,
 contact:()=>`<div class="wrap"><div class="page"><h1>Contact</h1><p>Phone / WhatsApp: <a href="tel:${CONFIG.phone.replace(/\s/g,"")}"><u>${CONFIG.phone}</u></a><br>Email: <a href="mailto:${CONFIG.email}"><u>${CONFIG.email}</u></a></p><form id="ctf" class="card-box"><div class="fld"><label>Name</label><input name="name" required></div><div class="fld"><label>Email</label><input name="email" type="email" required></div><div class="fld"><label>Message</label><textarea name="msg" rows="4" required></textarea></div><button class="btn wa">Send via WhatsApp</button></form></div></div>`};
function route(){const h=(location.hash||"#/").slice(2).split("/"),r=h[0];let html;Cart.load();
 if(r==="")html=home();else if(r==="shop"){const c=h[1];const cat=CATS.find(x=>x[0]===c);html=listing(cat?cat[1]:"Shop All",cat?"":"Export overstock, limited stock, no restocks.",filters[c]||(c?p=>p.cat===c:()=>true),c||"all")}
 else if(r==="new")html=listing("New Arrivals","Fresh drops this week.",p=>p.n,"")
 else if(r==="limited")html=listing("Limited Stock","Last pieces. No restock.",p=>p.l||p.stock<=5,"")
 else if(r==="sale")html=listing("Deals","Export overstock at sale prices.",isSale,"")
 else if(r==="wishlist")html=listing("Wishlist","Pieces you saved.",p=>Cart.wish.includes(p.id),"")
 else if(r==="p")html=detail(h[1]);else if(r==="checkout")html=checkout();
 else if(r==="admin")html=Admin.view();else if(pages[r])html=pages[r]();else html=home();
 $("#app").innerHTML=html;$("#nav").innerHTML=NAV.map(n=>`<a href="${n[1]}" class="${location.hash===n[1]||(!location.hash&&0)?"on":""}">${n[0]}</a>`).join("");
 $("#nav").classList.remove("on");window.scrollTo(0,0);document.title=r===""?"Aura Apparel | Premium Export Fashion | I-8 Markaz, Islamabad":"Aura Apparel | "+(r==="p"&&find(h[1])?find(h[1]).name:r[0].toUpperCase()+r.slice(1));
 Cart.badge();if(r==="admin")Admin.bind()}
function footer(){$("#ftr").innerHTML=`<div><div class="logo" style="color:#fff;margin-bottom:12px">AURA APPAREL</div><p>Premium Export Apparel. Unexpected Prices.</p><p>${CONFIG.phone}<br>${CONFIG.email}</p></div><div><h4>Shop</h4>${NAV.slice(0,6).map(n=>`<a href="${n[1]}">${n[0]}</a>`).join("")}</div><div><h4>Info</h4><a href="#/stores">Stores</a><a href="#/about">About & FAQ</a><a href="#/contact">Contact</a><a href="#/admin">Admin (demo)</a></div><div><h4>Follow</h4>${Object.entries(CONFIG.social).map(s=>`<a href="${s[1]}" target="_blank" rel="noopener">${s[0][0].toUpperCase()+s[0].slice(1)}</a>`).join("")}<p style="margin-top:12px;font-size:12px">Shop 14/15 Zakki Plaza & Shop 20 Plaza 2000, I-8 Markaz, Islamabad</p></div>`}
document.addEventListener("click",e=>{const t=e.target.closest("button,[data-color],a");if(!t)return;const D=t.dataset;
 if(D.close!==undefined||t.id==="ov")Cart.close();
 if(D.go)location.hash=D.go;
 if(D.heart){Cart.toggleWish(D.heart);if(location.hash.startsWith("#/wishlist")||location.hash.startsWith("#/p/"))route();else t.textContent=Cart.wish.includes(D.heart)?"♥":"♡"}
 if(D.q){const[k,d]=D.q.split(":");Cart.setQty(k,+d);if(location.hash==="#/checkout")route()}
 if(D.rm){Cart.remove(D.rm);if(location.hash==="#/checkout")route()}
 if(D.size){sel.size=D.size;document.querySelectorAll("[data-size]").forEach(b=>b.classList.toggle("on",b===t))}
 if(D.color){sel.color=D.color;document.querySelectorAll("[data-color]").forEach(b=>b.classList.toggle("on",b===t));$("#cn").textContent=D.color}
 if(D.th!==undefined){$("#mi").src=t.src;document.querySelectorAll("[data-th]").forEach(b=>b.classList.toggle("on",b===t))}
 if(D.add){Cart.add(D.add,sel.size,sel.color);toast("Added to bag")}
 if(D.clear!==undefined){query="";route()}
 if(D.ac)Admin.act(D.ac)});
document.addEventListener("change",e=>{if(e.target.id==="sort"){sort=e.target.value;route()}});
document.addEventListener("submit",e=>{const f=e.target;if(f.id==="cf"){e.preventDefault();order(f)}
 if(f.id==="ctf"){e.preventDefault();const d=Object.fromEntries(new FormData(f));window.open("https://wa.me/"+CONFIG.whatsapp+"?text="+encodeURIComponent(`Message from ${d.name} (${d.email}):\n${d.msg}`),"_blank");f.reset();toast("Opening WhatsApp...")}
 if(f.id==="sForm"){e.preventDefault();query=$("#sIn").value;f.hidden=true;location.hash==="#/shop"?route():location.hash="#/shop"}});
$("#burger").onclick=()=>$("#nav").classList.toggle("on");$("#sBtn").onclick=()=>{const f=$("#sForm");f.hidden=!f.hidden;if(!f.hidden)$("#sIn").focus()};
$("#bagBtn").onclick=()=>Cart.open();$("#annX").onclick=()=>$("#ann").remove();$("#annText").textContent=CONFIG.announcement;
addEventListener("hashchange",route);addEventListener("keydown",e=>{if(e.key==="Escape")Cart.close()});
Cart.load();Cart.render();footer();route();
